import './globals.css'
import { Inter } from 'next/font/google'
import EncabezadoComponent from "@/app/Encabezado/Encabezado.component";
import FooterComponent from "@/app/Footer/Footer.component";
import MenuComponent from "@/app/Menu/Menu.component";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <EncabezadoComponent/>
      <MenuComponent/>
      <FooterComponent/>
      {children}
      </body>
    </html>
  )
}
